[package]
name = "builder"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
regex = { version = "1.7.3", default-features = false, features = ["std", "unicode-perl"] }
zip = "0.6.4"
flate2 = { version = "1.0.25", features = ["zlib"], default-features = false }
