[package]
name = "rune-benches"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["macros"] }
criterion = "0.4.0"

rune = { path = "../crates/rune", features = ["bench"] }
rune-tests = { path = "../tests", default-features = false }

[[bench]]
name    = "bench_main"
harness = false
