name: Nightly Build

on:
  schedule:
    - cron: '* 1 * * *'
  push:
    branches:
      - nightly

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --workspace --all-targets
    - run: cargo test --workspace --doc
    - run: cargo run --bin rune -- check --recursive --experimental scripts
    - run: cargo run --bin rune -- test --recursive --experimental scripts
    - run: cargo run --manifest-path tools/builder/Cargo.toml -- --channel nightly
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: nightly
        files: target/upload/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
