name: Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      channel:
        description: 'release to perform'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly
        - release
      skip_tests:
        description: 'skip tests'
        required: true
        default: false
        type: boolean
  push:
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{env.TAG}}
    steps:
    - run: echo "TAG=$(date --iso -u)" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/release' || github.event.inputs.channel == 'release'
    - run: echo "TAG=nightly" >> $GITHUB_ENV
      if: github.event_name == 'schedule'
    - run: echo "TAG=${{github.event.inputs.channel}}" >> $GITHUB_ENV
      if: github.event_name != 'schedule' && github.ref != 'refs/heads/release'

  test:
    runs-on: ubuntu-latest
    if: ${{!github.event.inputs.skip_tests}}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --workspace --all-targets
    - run: cargo test --workspace --doc
    - run: cargo run --bin rune -- check --recursive --experimental scripts
    - run: cargo run --bin rune -- test --recursive --experimental scripts

  build:
    needs: [tag, test]
    runs-on: ${{matrix.os}}
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - run: 'echo "TAG: ${{needs.tag.outputs.tag}}"'
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo run -p builder -- --channel ${{needs.tag.outputs.tag}}
    - uses: actions/upload-artifact@v1
      with:
        name: dist-${{matrix.os}}
        path: dist

  publish:
    needs: [tag, build]
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "TAG: ${{needs.tag.outputs.tag}}"'
    - uses: actions/download-artifact@v1
      with: {name: dist-macos-latest, path: dist}
    - uses: actions/download-artifact@v1
      with: {name: dist-windows-latest, path: dist}
    - uses: actions/download-artifact@v1
      with: {name: dist-ubuntu-latest, path: dist}
    - name: Publish Release
      uses: ./.github/actions/github-release
      with:
        files: "dist/*"
        name: ${{needs.tag.outputs.tag}}
        token: ${{secrets.GITHUB_TOKEN}}
